require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  test-prof: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false
